
version: "3"
services:
    go-docker-image:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: go_test
        ports:
            - "9100:9100"
        volumes:
            - ./src:/app
